### ISSUE TITLE
Can't open link.

### ISSUE THREAD

**Issue by ChrisHubb** [sdebarun/python-sendmail#1]

**Comment by sdebarun** [comment]
Hello!

Can you please give more details about the issue? Like what  is shown while trying to open the link. I have tried to open it incognito mode too in Google Chrome and it is working.

**Comment by ChrisHubb** [comment]
It just keeps on loading... Forever

**Comment by sdebarun** [comment]
Thanks for the update. It is hard to understand the reason. I have no redirect in the code so I think the issue might be releated to github itself. But if you load the page with the network tab open, and check "Preserve log" you might be able to see what is going on. and what is redirecting you where. 

You can try some other browsers too or private/incognito mode of browsers to see if the problem persists or not.

In the meantime if you like to take a look in the script please try the following links,
[main.py](https://replit.com/@sdebarun/Mailpy#main.py) - go to the code tab for  the code. Please note that output will not work as no credentials have been passed to the script.
[Sendmail raw code](https://raw.githubusercontent.com/sdebarun/python-sendmail/main/main.py)

Please update me if any of the above link is working or not. and what you see in the network tab.

**Comment by sdebarun** [comment]
Hope those suggestions helped you. I am closing this issue but please feel free to reopen the issue.
